apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-demo

spec:
  replicas: 2
  selector:
    matchLabels:
      app: cm-demo
  template:
    metadata:
      labels:
        app: cm-demo
    spec:
      containers:
        - name: app
          image: busybox
          command: ["sh","-c","sleep 3600"]
          envFrom:
            - configMapRef:
                name: demo-config
